http:
  middlewares:
    # General circuit breaker for backend services
    backend-circuit-breaker:
      circuitBreaker:
        expression: "NetworkErrorRatio() > 0.20 || ResponseCodeRatio(500, 600, 0, 600) > 0.30"
        checkPeriod: "10s"
        fallbackDuration: "30s"
        recoveryDuration: "10s"
        
    # Specific circuit breaker for AI endpoints
    ai-circuit-breaker:
      circuitBreaker:
        expression: "NetworkErrorRatio() > 0.25 || ResponseCodeRatio(500, 600, 0, 600) > 0.40"
        checkPeriod: "15s"
        fallbackDuration: "45s"
        recoveryDuration: "15s"
        
    # Database circuit breaker
    db-circuit-breaker:
      circuitBreaker:
        expression: "NetworkErrorRatio() > 0.10 || ResponseCodeRatio(500, 600, 0, 600) > 0.25"
        checkPeriod: "5s"
        fallbackDuration: "20s"
        recoveryDuration: "10s"